# Generated by Django 4.1.4 on 2023-03-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_authors_book_publisher_alter_comment_author_reader_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='bookstore',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='favorite_book',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Bookstore',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
